# Generated by Django 4.2 on 2023-05-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments_forum',
            name='post_date',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_date',
            field=models.DateField(max_length=10),
        ),
    ]
