# Generated by Django 4.2 on 2023-05-12 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_alter_comments_forum_post_date_alter_posts_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='title',
        ),
        migrations.AlterField(
            model_name='categories_post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='comments_forum',
            name='body',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='comments_forum',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.posts', verbose_name='Пост'),
        ),
        migrations.AlterField(
            model_name='comments_forum',
            name='post_date',
            field=models.DateField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='comments_forum',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='body',
            field=models.TextField(verbose_name='Пост'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.categories_post', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_date',
            field=models.DateField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.topics', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='posts_img_forum',
            name='img',
            field=models.ImageField(upload_to='images/posts', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='posts_img_forum',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.posts', verbose_name='Пост'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.categories_post', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
