# Generated by Django 4.2 on 2023-05-12 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0004_remove_posts_img_forum_img_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories_post',
            options={'ordering': ['title'], 'verbose_name': ('Категория поста',), 'verbose_name_plural': 'Категории постов'},
        ),
        migrations.AlterModelOptions(
            name='comments_forum',
            options={'ordering': ['post_date'], 'verbose_name': ('Комментарий поста',), 'verbose_name_plural': 'Комментарии постов'},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['post_date'], 'verbose_name': ('Пост',), 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterModelOptions(
            name='posts_img_forum',
            options={'ordering': ['post'], 'verbose_name': ('Изображение поста',), 'verbose_name_plural': 'Изображения постов'},
        ),
        migrations.AlterModelOptions(
            name='topics',
            options={'ordering': ['category'], 'verbose_name': ('Тема',), 'verbose_name_plural': ('Темы',)},
        ),
        migrations.AddField(
            model_name='posts_img_forum',
            name='img',
            field=models.ImageField(blank=True, db_index=True, upload_to='images/posts', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='categories_post',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='comments_forum',
            name='body',
            field=models.TextField(blank=True, db_index=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='comments_forum',
            name='post',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='forum.posts', verbose_name='Пост'),
        ),
        migrations.AlterField(
            model_name='comments_forum',
            name='post_date',
            field=models.DateField(blank=True, db_index=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='comments_forum',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='body',
            field=models.TextField(blank=True, db_index=True, verbose_name='Пост'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='forum.categories_post', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_date',
            field=models.DateField(blank=True, db_index=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='topic',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='forum.topics', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='posts_img_forum',
            name='post',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='forum.posts', verbose_name='Пост'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='forum.categories_post', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
