# Generated by Django 4.2 on 2023-05-12 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_categories_post_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories_post',
            options={'ordering': ['title'], 'verbose_name': 'Категория поста', 'verbose_name_plural': 'Категории постов'},
        ),
        migrations.AlterModelOptions(
            name='comments_forum',
            options={'ordering': ['post_date'], 'verbose_name': 'Комментарий поста', 'verbose_name_plural': 'Комментарии постов'},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['post_date'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterModelOptions(
            name='posts_img_forum',
            options={'ordering': ['post'], 'verbose_name': 'Изображение поста', 'verbose_name_plural': 'Изображения постов'},
        ),
        migrations.AlterModelOptions(
            name='topics',
            options={'ordering': ['category'], 'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
    ]
