# Generated by Django 4.2 on 2023-05-12 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albums',
            name='url_spotify',
        ),
        migrations.RemoveField(
            model_name='songs',
            name='url_spotify',
        ),
        migrations.AddField(
            model_name='artists',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='albums',
            name='artist',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.artists'),
        ),
        migrations.AlterField(
            model_name='albums',
            name='date_release',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='albums',
            name='genre',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.genres'),
        ),
        migrations.AlterField(
            model_name='albums',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='albums',
            name='url_vk',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='albums',
            name='url_yandex',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='albums_img',
            name='album',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.albums'),
        ),
        migrations.AlterField(
            model_name='albums_img',
            name='img',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='articles',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.categories_news'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist_img',
            name='artist',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.artists'),
        ),
        migrations.AlterField(
            model_name='artist_img',
            name='img',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='artists',
            name='country',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='artists',
            name='genre',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.genres'),
        ),
        migrations.AlterField(
            model_name='artists',
            name='history',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artists',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='categories_news',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='comments_news',
            name='article',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.articles'),
        ),
        migrations.AlterField(
            model_name='comments_news',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='comments_news',
            name='date',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='comments_news',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='concects_img',
            name='concert',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.concerts'),
        ),
        migrations.AlterField(
            model_name='concects_img',
            name='img',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='concerts',
            name='date_of',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='concerts',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='concerts',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='concerts',
            name='time_of',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='concerts',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='genres',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='news_img',
            name='article',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.articles'),
        ),
        migrations.AlterField(
            model_name='news_img',
            name='img',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='songs',
            name='album',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.albums'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='artist',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.artists'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='duration',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='songs',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='songs',
            name='url_vk',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='songs',
            name='url_yandex',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
