# Generated by Django 4.2 on 2023-05-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_albums_url_spotify_remove_songs_url_spotify_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='date_release',
            field=models.DateField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='comments_news',
            name='date',
            field=models.DateField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='concerts',
            name='date_of',
            field=models.DateField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='concerts',
            name='time_of',
            field=models.TimeField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='songs',
            name='duration',
            field=models.TimeField(blank=True, max_length=6),
        ),
    ]
