# Generated by Django 4.2 on 2023-05-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_articles_options_alter_albums_artist_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albums',
            options={'ordering': ['artist'], 'verbose_name': ('Альбом',), 'verbose_name_plural': 'Альбомы'},
        ),
        migrations.AlterModelOptions(
            name='albums_img',
            options={'ordering': ['album'], 'verbose_name': ('Изображение альбома',), 'verbose_name_plural': 'Изображения альбомов'},
        ),
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ['date'], 'verbose_name': ('Новость',), 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='artist_img',
            options={'ordering': ['artist'], 'verbose_name': ('Изображение исполнителя',), 'verbose_name_plural': 'Изображение исполнителей'},
        ),
        migrations.AlterModelOptions(
            name='artists',
            options={'ordering': ['name'], 'verbose_name': ('Исполнитель',), 'verbose_name_plural': 'Исполнители'},
        ),
        migrations.AlterModelOptions(
            name='categories_news',
            options={'ordering': ['title'], 'verbose_name': ('Категория',), 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='comments_news',
            options={'ordering': ['date'], 'verbose_name': ('Комментарий',), 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='concects_img',
            options={'ordering': ['id'], 'verbose_name': ('Изображение концерта',), 'verbose_name_plural': 'Изображения концертов'},
        ),
        migrations.AlterModelOptions(
            name='concerts',
            options={'ordering': ['date_of'], 'verbose_name': ('Концерт',), 'verbose_name_plural': 'Концерты'},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={'ordering': ['title'], 'verbose_name': ('Жанр',), 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='news_img',
            options={'ordering': ['article'], 'verbose_name': ('Изображение новости',), 'verbose_name_plural': 'Изображения новостей'},
        ),
        migrations.AlterModelOptions(
            name='songs',
            options={'ordering': ['title'], 'verbose_name': ('Музыка',), 'verbose_name_plural': 'Музыка'},
        ),
        migrations.AlterField(
            model_name='albums',
            name='date_release',
            field=models.DateField(blank=True, db_index=True, max_length=200, verbose_name='Дата релиза'),
        ),
        migrations.AlterField(
            model_name='albums',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='albums',
            name='url_vk',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Ссылка на вк'),
        ),
        migrations.AlterField(
            model_name='albums',
            name='url_yandex',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Ссылка на yandex'),
        ),
        migrations.AlterField(
            model_name='albums_img',
            name='img',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='body',
            field=models.TextField(blank=True, db_index=True, verbose_name='Новость'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateField(blank=True, db_index=True, max_length=10, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='artist_img',
            name='img',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='artists',
            name='body',
            field=models.TextField(blank=True, db_index=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='artists',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='artists',
            name='history',
            field=models.TextField(blank=True, db_index=True, verbose_name='История'),
        ),
        migrations.AlterField(
            model_name='artists',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='categories_news',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='comments_news',
            name='body',
            field=models.TextField(blank=True, db_index=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='comments_news',
            name='date',
            field=models.DateField(blank=True, db_index=True, max_length=10, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='concects_img',
            name='img',
            field=models.ImageField(db_index=True, upload_to='images/concerts', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='concerts',
            name='date_of',
            field=models.DateField(blank=True, db_index=True, max_length=10, verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='concerts',
            name='link',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='concerts',
            name='location',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='concerts',
            name='time_of',
            field=models.TimeField(blank=True, db_index=True, max_length=10, verbose_name='Время проведения'),
        ),
        migrations.AlterField(
            model_name='concerts',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='genres',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='news_img',
            name='img',
            field=models.ImageField(blank=True, db_index=True, upload_to='images/news', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='duration',
            field=models.TimeField(blank=True, db_index=True, max_length=6, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='url_vk',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Ссылка на вк'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='url_yandex',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Ссылка на yandex'),
        ),
    ]
