# Generated by Django 4.2 on 2023-05-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_albums_options_alter_albums_img_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums_img',
            name='img',
            field=models.ImageField(blank=True, db_index=True, upload_to='images/albums', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='artist_img',
            name='img',
            field=models.ImageField(blank=True, db_index=True, upload_to='images/artists', verbose_name='Изображение'),
        ),
    ]
