# Generated by Django 4.2 on 2023-05-14 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_albums_artist_alter_albums_genre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories_news',
            options={'ordering': ['title'], 'verbose_name': 'Категория новости', 'verbose_name_plural': 'Категории новостей'},
        ),
        migrations.RemoveField(
            model_name='songs',
            name='url_vk',
        ),
        migrations.RemoveField(
            model_name='songs',
            name='url_yandex',
        ),
    ]
