# Generated by Django 4.2 on 2023-05-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_categories_post_posts_topics_posts_img_forum_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories_post',
            options={'ordering': ['title'], 'verbose_name': '[ФОРУМ] Категория поста', 'verbose_name_plural': '[ФОРУМ] Категории постов'},
        ),
        migrations.AlterModelOptions(
            name='comments_forum',
            options={'ordering': ['post_date'], 'verbose_name': '[ФОРУМ] Комментарий поста', 'verbose_name_plural': '[ФОРУМ] Комментарии постов'},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['post_date'], 'verbose_name': '[ФОРУМ] Пост', 'verbose_name_plural': '[ФОРУМ] Посты'},
        ),
        migrations.AlterModelOptions(
            name='topics',
            options={'ordering': ['category'], 'verbose_name': '[ФОРУМ] Тема', 'verbose_name_plural': '[ФОРУМ] Темы'},
        ),
        migrations.AddField(
            model_name='posts',
            name='img',
            field=models.ImageField(blank=True, db_index=True, upload_to='images/posts', verbose_name='Изображение'),
        ),
        migrations.DeleteModel(
            name='Posts_img_forum',
        ),
    ]
