# Generated by Django 4.2 on 2023-05-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_categories_post_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='topic',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Тема'),
        ),
        migrations.DeleteModel(
            name='Topics',
        ),
    ]
