# Generated by Django 4.2 on 2023-05-16 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_posts_topic_delete_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments_forum',
            name='post_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.datetime(2023, 5, 16, 12, 21, 44, 226134), verbose_name='Дата публикации'),
        ),
    ]
